controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

app_animations:
    resource: '../src/Controller/AnimationsController.php'
    type: annotation